---
- hosts: localhost
  gather_facts: no

  tasks:
    - name: Create a k8s imagestream from file
      kubernetes.core.k8s:
         state: present
         src: files/duckhunt-is_centos7-s2i-nodejs.yaml