---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: Create a k8s namespace
      kubernetes.core.k8s:
         name: carlosds
         api_version: v1
         kind: Namespace
         state: present
         kubeconfig: kube/kubeconfig