apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: duckhunt-js
    app.kubernetes.io/component: duckhunt-js
    app.kubernetes.io/instance: duckhunt-js
  name: duckhunt-js
  namespace: default
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: duckhunt-js:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      uri: https://github.com/vrutkovs/DuckHunt-JS
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: centos7-s2i-nodejs:12.x
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers:
    - type: ImageChange
      imageChange: {}
    - type: ConfigChange