apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: duckhunt-js
    app.kubernetes.io/component: duckhunt-js
    app.kubernetes.io/instance: duckhunt-js
  name: centos7-s2i-nodejs
  namespace: default
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations:
      openshift.io/imported-from: nodeshift/centos7-s2i-nodejs:12.x
    from:
      kind: DockerImage
      name: nodeshift/centos7-s2i-nodejs:12.x
    generation: 2
    importPolicy: {}
    name: 12.x
    referencePolicy:
      type: Source